[tool.poetry]
name = "hetgpy"
version = "0.1.0"
description = "Python implementation of hetGP"
authors = ["David O'Gara <david.ogara@wustl.edu>"]
readme = "README.md"
packages = [ { include = "**/*.py", from = "."  }]

exclude = [
    "eigen/*",
    "tests/*",
    "compare/*",
    "notebooks/*",
    "mplstyle/*",
    "hetGP/*"
]



[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"
scipy = "^1.11.4"
rpy2 = "^3.5.14"
pytest = "^7.4.3"
pyyaml = "^6.0.1"
matplotlib = "^3.8.2"
cython = "^3.0.6"
pybind11 = "^2.11.1"
quarto = "^0.1.0"
mkdocs = "^1.5.3"
sphinx = "^7.2.6"
numba = "^0.58.1"
cppimport = "^22.8.2"
pytest-xdist = "^3.5.0"
build = "^1.0.3"


[tool.poetry.group.dev.dependencies]
pandas = "^2.1.3"
dash = "^2.14.1"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[build-system]
requires = ["setuptools>=61.0","wheel", "pybind11~=2.11.1"]
build-backend = "poetry.core.masonry.api"




