[tool.poetry]
name = "hetgpy"
version = "0.1.0"
description = ""
authors = ["David O'Gara <david.ogara@wustl.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"
scipy = "^1.11.4"
rpy2 = "^3.5.14"
pytest = "^7.4.3"
pybind11 = "^2.11.1"
cppimport = "^22.8.2"
boost = "^0.1"


[tool.poetry.group.dev.dependencies]
pandas = "^2.1.3"
dash = "^2.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
