[tool.poetry]
name = "hetgpy"
version = "0.1.0"
description = "Python implementation of hetGP"
authors = ["David O'Gara <david.ogara@wustl.edu>"]
readme = "README.md"
build = "build.py"


include = [
    {path = "src", format = ["sdist", "wheel"]},
    {path = "tests", format = ["sdist", "wheel"]}  
]

exclude = [
    "eigen/*",
    "compare/*",
    "notebooks/*",
    "mplstyle/*",
    "hetGP/*"
]



[tool.poetry.dependencies]
python = "~3.9"
numpy = "^1.20.2"
scipy = "^1.6.2"
pytest = "^7.4.3"
cython = "^3.0.6"
pybind11 = "^2.11.1"
build = "^1.2.0"
cppimport = "^22.8.2"
joblib = "^1.3.2"
setuptools = "^69.2.0"
setuptools-cpp = "^0.1.0"
jax = "^0.4.28"
jaxlib = "^0.4.28"


[tool.poetry.group.dev.dependencies]
dash = "^2.14.1"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"
sphinx = "^7.2.6"
numpydoc = "^1.6.0"
pip = "^23.3.2"
install = "^1.3.5"
sphinx-rtd-theme = "^2.0.0"
pymc = "^5.10.4"
gpytorch = "^1.11"
rpy2 = "^3.5.16"
matplotlib = "^3.8.3"



[build-system]
build-backend = "setuptools.build_meta"
requires = ["poetry>=0.12", "setuptools", "wheel", "setuptools-cpp","pybind11"]




