[tool.poetry]
name = "hetgpy"
version = "0.1.0"
description = "Python implementation of hetGP"
authors = ["David O'Gara <david.ogara@wustl.edu>"]
readme = "README.md"
packages = [ { include = "**/*.py", from = "."  }]

include = [
    "hetgpy/*",
    "tests/*"
]

exclude = [
    "eigen/*",
    "tests/*",
    "compare/*",
    "notebooks/*",
    "mplstyle/*",
    "hetGP/*"
]



[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.2"
scipy = "^1.11.4"
rpy2 = "^3.5.14"
pytest = "^7.4.3"
matplotlib = "^3.8.2"
cython = "^3.0.6"
pybind11 = "^2.11.1"
quarto = "^0.1.0"
build = "^1.0.3"
cppimport = "^22.8.2"
jupyter = "^1.0.0"


[tool.poetry.group.dev.dependencies]
dash = "^2.14.1"
ipykernel = "^6.27.1"
jupyter = "^1.0.0"

[build-system]
requires = ["pybind11"]




