[project]
name = "hetgpy"
version = "0.1.0"
description = "Python implementation of hetGP"
authors = [
{name="David O'Gara", email="david.ogara@wustl.edu"},
]
readme = "README.md"
requires-python = ">3.10"
dependencies = ['jax>=0.4.28,<0.5.0',
 'jaxlib>=0.4.28,<0.5.0',
 'joblib>=1.3.2,<2.0.0',
 'matplotlib>=3.9.1,<4.0.0',
 'numba>=0.60.0,<0.61.0',
 'numpy>=1.20.2,<2.0.0',
 'scipy==1.14.0',
 'tqdm>=4.66.4,<5.0.0']

[tool.setuptools]
packages=['hetgpy']




[build-system]
build-backend = "setuptools.build_meta"
requires = ["poetry>=0.12", "setuptools", "wheel", "setuptools-cpp","pybind11"]




