[project]
name = "hetgpy"
version = "0.1.0"
description = "Python implementation of hetGP"
authors = [
{name="David O'Gara", email="david.ogara@wustl.edu"},
]
readme = "README.md"
requires-python = ">3.10"
dependencies = [
 'numpy>=1.20.2,<2.0.0',
 'scipy>=1.14.0',
 'matplotlib>=3.9.1,<4.0.0']

[tool.setuptools]
packages=['hetgpy','tests']



[build-system]
build-backend = "setuptools.build_meta"
requires = ["poetry>=0.12", "setuptools", "wheel", "setuptools-cpp","pybind11"]




