# This workflow will install Python dependencies and build the package
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build hetGPy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
        python-version: ["3.10"]
        include:
        - os: ubuntu-latest
          os-name: Linux
          pip-cache-path: ~/.cache/pip
        - os: macos-11
          os-name: MacOS
          pip-cache-path: ~/Library/Caches/pip
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps: 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.config.py }}"

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel build
          python -m build
      

     
