name: Wheels

on:
  workflow_dispatch:
jobs:

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Optional, use if you use setuptools_scm
          submodules: true # Optional, use if you have submodules
  
      - name: Build SDist
        run: pipx run build --sdist
  
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env: 
      CIBW_BUILD: cp310-* cp311-* cp312-* cp13-*
      CIBW_ARCHS: auto64
      CIBW_TEST_REQUIRES: pytest
      CIBW_TEST_COMMAND: "pytest {project}/tests/test*.py"
      CIBW_TEST_EXTRAS: ""
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14] # macos-13, macos-13, windows-latest
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: pypa/cibuildwheel@v2.21
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
