name: Build and Test

on: push

env:
  OPENBLAS_NUM_THREADS: 1
  OMP_NUM_THREADS: 1

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for $${ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest'] # [ubuntu-latest, windows-latest, macos-14]
        python-version: ['3.10'] #, '3.11', '3.12','3.13']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install dev dependencies
        run: python -m pip install -r requirements_testing.txt
      - name: Handle eigen
        run: git submodule update --init --recursive
      - name: Build package
        run: pip install -e .
      - name: Test
        run: pytest -k "not test_rpy2" # run basic tests (not those in rpy2 folder
      - name: Run Intro Example
        run: jupyter execute examples/00-hetGPy-Intro.ipynb
      - name: Run Motorcycle Example
        run: jupyter execute examples/01-mcycle-example.ipynb
      #- name: Run SIR Example
      #  run: jupyter execute examples/02-SIR-example.ipynb
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
